### ISSUE TITLE
Instructor Insights: remove pie charts

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#160]
Some Instructor Insights pages have a pie chart depicting the breakdown of assessment and/or how student time was spent. The chart is constructed using a canvas element and JavaScript, which is not getting parsed correctly. 

In discussing with the OCW team, we decided that the pie charts weren't worth maintaining. They are a decorative element that is no longer needed. 

#### Compare: 

Legacy OCW, from https://ocw.mit.edu/courses/civil-and-environmental-engineering/1-74-land-water-food-and-climate-fall-2020/instructor-insights/

<img width="393" alt="image" align="left" src="https://user-images.githubusercontent.com/430126/104220708-e2b8c500-540d-11eb-9be7-9365a0148bf0.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/430126/104221255-a9cd2000-540e-11eb-99ba-34072e59a012.png">

Current OCWNext, from https://ocwnext-rc.odl.mit.edu/courses/1-74-land-water-food-and-climate-fall-2020/sections/instructor-insights/

<img width="689" alt="image" src="https://user-images.githubusercontent.com/430126/104220754-f401d180-540d-11eb-87d0-6f65b097bdce.png">

<img width="686" alt="image" src="https://user-images.githubusercontent.com/430126/104221399-d1bc8380-540e-11eb-8126-12540079cc47.png">

#### Acceptance criteria

- [x] come up with a plan and review with team
- [x] omit pie chart from rendered HTML
- [x] omit color key (img with very long alt tag) from rendered HTML
- [x] keep all other text and headings

**Comment by gumaerc** [comment]
RFC here: https://docs.google.com/document/d/1zzaRmNPQUA7PukyQQWp9W7t1sslOohKVUDQzT93TSiQ/edit#

**Comment by pdpinch** [comment]
Thanks, I responded to what I think was a question I the doc.
