### ISSUE TITLE
Course Home link is missing from left nav

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#162]
### Steps to Reproduce

See https://ocwnext.odl.mit.edu/courses/21a-461-what-is-capitalism-fall-2013/ 

### Expected Behavior

"Course Home" link text should be visible. 

### Actual Behavior

there's anchor tag, but no link text

**Comment by pdpinch** [comment]
@gumaerc I opened this when you told me about the issue, but I think @Ferdi prefers it as is, with "course home" omitted. Please check before working on it.

**Comment by gumaerc** [comment]
I chatted with Ferdi about this and it seems the plan is to remove Course Home from the left nav and instead make the course title a clickable link that brings you to the course home.
