### ISSUE TITLE
Missing subsection page for 18-06sc-linear-algebra-fall-2011

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#179]
### Steps to Reproduce

Legacy URL: https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/least-squares-determinants-and-eigenvalues/projections-onto-subspaces/problem-solving-projection-onto-subspaces/
OCWNext URL gets a 404 for a similar URL. The UID for that page does not appear in the output parsed JSON except as a `parent_uid` so there is likely something we are overlooking. The parent page for that subsection is visible: https://ocwnext.odl.mit.edu/courses/18-06sc-linear-algebra-fall-2011/pages/least-squares-determinants-and-eigenvalues/projections-onto-subspaces/

### Screenshots
![Screenshot from 2021-01-28 16-42-27](https://user-images.githubusercontent.com/863262/106202438-f000de00-6187-11eb-900f-a57939bed016.png)

**Comment by noisecapella** [comment]
Two other similar cases:
 - https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011/unit-1/lecture-4-machine-interpretation-of-a-program/lecture-4-machine-interpretation-of-a-program
 - https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-00sc-introduction-to-computer-science-and-programming-spring-2011/unit-3/lecture-20-more-clustering/recitation-8-hierarchical-and-k-means-clustering

There are probably others, these are just the ones I found in the example course list.

**Comment by pdpinch** [comment]
I think these pages are artifacts of the Plone video publishing process, i.e. a video in the tabbed video player gets a page. I'm finding now that we _are_ publishing pages for these videos, but not necessarily at the expected URL. For example the content at https://ocw.mit.edu/courses/mathematics/18-06sc-linear-algebra-fall-2011/least-squares-determinants-and-eigenvalues/projections-onto-subspaces/problem-solving-projection-onto-subspaces/ seems to me the same as https://ocwnext.odl.mit.edu/courses/18-06sc-linear-algebra-fall-2011/sections/resource-index/problem-solving-projection-onto-subspaces/ 

But I haven't found links to these pages on the legacy site. @noisecapella how did you find them?

**Comment by noisecapella** [comment]
@pdpinch I think you're right, the pages exist but at different URLs
