### ISSUE TITLE
PDF links not working in some sections

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#180]
### Steps to Reproduce

Generate markdown for `18-06sc-linear-algebra-fall-2011` and spin the site up using `ocw-course-hugo-theme`.  Browse to `/courses/18-06sc-linear-algebra-fall-2011/sections/ax-b-and-the-four-subspaces/exam-1/`

### Expected Behavior

The links to the PDFs go to PDF viewer pages

### Actual Behavior

They 404

### Additional context

From the PR where this was discovered:

I encountered an issue here with the course 18-06sc-linear-algebra-fall-2011. There are a couple of sections that have links to PDF's that were not functioning. I dug into it and the HTML was being generated for them, so I was confused at first about what was wrong, but it seems the issue has to do with case sensitivity. The URL's are being rendered into the markdown with uppercase letters, and the markdown files themselves have uppercase letters in the filenames. However, it seems when Hugo generates the HTML it is lowercasing the filename (MIT18_06SCF11_ex1.md turns into a folder named mit18_06scf11_ex1 with an index.html inside) and it only works if you access the URL lower case.

**Comment by noisecapella** [comment]
When working on this issue we should also verify that the fix for this means that `21m-380-music-and-technology-sound-design-spring-2016/sections/syllabus` has a valid PDF link for for course entrance questionnaire

**Comment by noisecapella** [comment]
There's a PDF link that's broken here which also might get fixed by this: https://ocwnext.odl.mit.edu/courses/8-13-14-experimental-physics-i-ii-junior-lab-fall-2016-spring-2017/sections/experiments/raman-spectroscopy/ at the bottom with the text "Indistinguishable Particle Effects"
