### ISSUE TITLE
entire color key is removed with pie charts

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#189]
### Steps to Reproduce

Convert a course with an instructor insights section

### Expected Behavior

When pie charts with a color key are being converted, the key itself should be preserved and the images inside the key should be removed

**Comment by pdpinch** [comment]
For example, on https://ocwnext-rc.odl.mit.edu/courses/6-034-artificial-intelligence-fall-2010/sections/instructor-insights/ 

Current text:
> The students' grades were based on the following activities:
>
> “Spiritual” material refers to lectures not considered part of the core skill set; the “Right Now” material refers to lectures given by what’s-happening-right-now guest lecturers.

should instead be something like:

> The students' grades were based on the following activities:
>
> - 60% Assessment on core material
> - 20% Assessment on spiritual and Right Now talk material.
> - 20% Labs 
>
> “Spiritual” material refers to lectures not considered part of the core skill set; the “Right Now” material refers to lectures given by what’s-happening-right-now guest lecturers.
