### ISSUE TITLE
Integrate testing with hugo-course-publisher and assert HTML output

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#19]
As a developer, I'd like to have tests which can convert input course JSON data to HTML, using ocw-to-hugo to convert to markdown and hugo-course-publisher to convert to HTML. This would allow us to assert the HTML output with enzyme and other JS tools.

#### Acceptance Criteria:

Vague at the moment

**Comment by pdpinch** [comment]
Since hugo-course-publisher isn't in use any more, I'm going to close this. If there's still need for integration testing, please open a new issue.
