### ISSUE TITLE
Support resource links

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-to-hugo#192]
I think these are relatively rare, but I saw one in 12.800: `/resources/res-12-001-topics-in-fluid-dynamics-spring-2010`. It looks like we can just rewrite with `/courses` instead of `/resources`

**Comment by pdpinch** [comment]
That should be fine, because we’re moving all the legacy “supplemental resources” under the courses tree (they use the same template). 

>  It looks like we can just rewrite with /courses instead of /resources

**Comment by noisecapella** [comment]
Closing, duplicate of #360
