### ISSUE TITLE
broken YouTube links

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#207]
See https://ocwnext.odl.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/sections/week-1-kinematics/3.1-coordinate-system-and-position-vector-in-2d/

and compare to https://ocw.mit.edu/courses/physics/8-01sc-classical-mechanics-fall-2016/week-1-kinematics/3.1-coordinate-system-and-position-vector-in-2d

comparing the source HTML, it appears that the YouTube, `Q3v_2znHCvg` is getting truncated at the `_` (underscore).

**Comment by gumaerc** [comment]
This ended up being an issue with how the custom OCW YouTube tags get transformed into a Hugo youtube shortcode before going through turndown.  Turndown escapes characters in content that markdown would interpret as a formatting rule, like an underscore.  I'm working on a PR to make sure that the YouTube ID's are written without escaping any characters.
