### ISSUE TITLE
Relative links to course sections

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#22]
### Steps to Reproduce

Generate markdown using the standard sample courses

### Expected Behavior

All links to other course sections function as expected and bring you to that section.

### Actual Behavior

Some links, for example, the "proofs" links in 6-042j-mathematics-for-computer-science-spring-2015 lead to a 404.

These links are relative in the source json and not `resolveuid` links.  We will need a way to recognize and deal with these.

**Comment by aliceriot** [comment]
found a big table here: http://localhost:3000/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/sections/fluid-mechanics/ (in hugo-course-publisher) which has a bunch of hardcoded links to PDFs which have the correct path for OCW but not for hugo
