### ISSUE TITLE
Course pages: External links missing from course navigation

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#229]
### Steps to Reproduce

Compare OCW next: 

https://ocwnext.odl.mit.edu/courses/res-env-004-mit-climate-portal-fall-2020/

to OCW legacy:

https://ocw.mit.edu/resources/res-env-004-mit-climate-portal-fall-2020/

### Expected Behavior

- [ ] menu items and links should be included in the processed json
- [ ] menu items should appear in the left hand nav on desktop
- [ ] menu items should appear in course materials menu on mobile 

### Actual Behavior

- both links are missing

**Comment by gumaerc** [comment]
@pdpinch I formatted this into CSV and uploaded it to Google Sheets here:

https://docs.google.com/spreadsheets/d/1jGUgSR2kyLu2oewOZt7Z1b8gK3uzQl5I9E9P8rKsC3Y/edit?usp=sharing

A couple questions to consider:
 
In some of the courses, the external nav link doesn't seem to be specified on every page.  For example:

https://ocw.mit.edu/courses/mathematics/18-031-system-functions-and-the-laplace-transform-spring-2019/instructor-insights/

If you click any of the links to the subsections of Instructor Insights, the external link in the nav to "Online Publication" disappears.  This feels unintentional, and I'm assuming the intent is for the external nav link to just be there on every page but I wanted to make sure.

A couple of the links are relative to the site root, for example:

` /OcwExport/Akamai/resources/edics/index.htm`

There are two courses that have this, and if you look at them on the live OCW site they point to this:

https://ocw.mit.edu/ans7870/resources/edics/index.htm

Either way, this won't work in the Hugo generated site.  `ans7870` is something we're going to have to discuss at some point, as there are a number of links pointing to this content (hosted on Akamai I believe?) and we'll need a way to rewrite them.

**Comment by pdpinch** [comment]
> In some of the courses, the external nav link doesn't seem to be specified on every page. 

I'll ask to see if this is deliberate.

**Comment by pdpinch** [comment]
> A couple of the links are relative to the site root, for example:

This is an artifact of having collected the links from the mirror drive. These days https://ocw.mit.edu/ans7870/ is routed to an S3 bucket and the URLs should be stable going into the future. Hugo isn't involved in publishing content to that bucket.

**Comment by pdpinch** [comment]
> In some of the courses, the external nav link doesn't seem to be specified on every page.

I've confirmed this is an error. The link should be on all pages on a course if it's on one.
