### ISSUE TITLE
Render legacy "pop-up" videos as links

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#235]
The legacy OCW site has three templates for rendering videos. We recently added the video `template_type` field to OCW parsed JSON in https://github.com/mitodl/ocw-data-parser/pull/132.

In OCW Next, the popup video template should be rendered as a link to a single video page. 

Currently it is rendering as an embedded video, which is breaking some page layouts. For example [this page from a scholar course](https://ocwnext.odl.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/sections/1.-differentiation/part-a-definition-and-basic-rules/session-3-derivative-as-rate-of-change/) and [this resource index table](https://ocwnext.odl.mit.edu/courses/6-00sc-introduction-to-computer-science-and-programming-spring-2011/sections/resource-index/).

### related issues 

- embedded video player should include a link to single player page
- replace YouTube player with customized video.js player

**Comment by pdpinch** [comment]
@gumaerc I see the videos getting rendered as links instead of embeds on this page:

https://ocwnext-rc.odl.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/sections/1.-differentiation/part-a-definition-and-basic-rules/session-3-derivative-as-rate-of-change/

**but** the links are returning S3 errors, for example:

https://ocwnext-rc.odl.mit.edu/sections/1.-differentiation/part-a-definition-and-basic-rules/session-3-derivative-as-rate-of-change/clip-2-rates-of-change/

**Comment by pdpinch** [comment]
another example, just in case: 

https://ocwnext-rc.odl.mit.edu/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/sections/resource-index/ 

has a broken link to 

https://ocwnext-rc.odl.mit.edu/sections/resource-index/lecture-2-video/

I think the path is being calculated incorrectly.

**Comment by gumaerc** [comment]
Links fixed, PR's merged and released to prod.
