### ISSUE TITLE
Course description HTML

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#24]
### Steps to Reproduce

Generate markdown for any number of courses.  Inspect the course home page markdown in _index.md

### Expected Behavior

Either only markdown content is generated, or some other solution (shortcode, allowing raw html) is implemented to make the page render properly in hugo-course-publisher

### Actual Behavior

Raw HTML is written into the markdown, which renders as text in hugo-course-publisher.

### Related Issues

https://github.com/mitodl/hugo-course-publisher/issues/80

**Comment by aliceriot** [comment]
do we want to just pipe this through [safeHTML](https://gohugo.io/functions/safehtml/), or is that risky?

**Comment by gumaerc** [comment]
> do we want to just pipe this through [safeHTML](https://gohugo.io/functions/safehtml/), or is that risky?

We can do this.  I was maybe a little worried about being able to scrub incoming content if we end up using Netlify CMS.  If we do we could use a custom widget for fields that accept raw HTML and do the scrubbing there, and if we end up implementing our own content editing system we could handle it there.

**Comment by gumaerc** [comment]
This was addressed in @aliceriot 's mobile course home page PR
