### ISSUE TITLE
use correct title for faculty

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#254]
When listing the instructors in a course, the appropriate title should be used, instead of the current default "Prof."

Once https://github.com/mitodl/ocw-data-parser/issues/136 is fixed, we should see a "salutation" field come through, for example, in the course 8.01SC ([legacy](https://ocw.mit.edu/courses/physics/8-01sc-classical-mechanics-fall-2016/) and [nextgen](https://ocwnext.odl.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/)).

Salutations will not be available in all courses until we do a full site republish (or at least a full site export). 

#### Acceptance Criteria:

- [x] If there is a salutation in the processed course JSON, use it
- [x] if there is none, we can continue defaulting to "Prof."

**Comment by gumaerc** [comment]
This is now fixed and deployed to prod

**Comment by pdpinch** [comment]
I see this on prod ([for example, two Dr.'s on 8.01sc](https://ocwnext.odl.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/)), but I don't see it in the [search results](https://ocwnext.odl.mit.edu/search/?q=8.01sc%20%22classical%20mechanics%22).

Also, what will happen if we remove the "default" of using Prof.?

**Comment by gumaerc** [comment]
@mbertrand do you know what is required to update the salutation being used in the search results in Peter's link above?

@pdpinch If we remove the default of Prof. it will simply be just their name with no salutation, although currently I believe this is limited by not being able to re-export JSON from Plone for every single course.  Only the courses that have been re-exported have salutation to begin with.

**Comment by mbertrand** [comment]
The salutation is currently not included in search results, just first and last name.  It is added after the fact on the frontend in both [ocw-www](https://github.com/mitodl/ocw-www/blob/main/src/js/components/SearchResult.js#L120) and open-discussions.  If it becomes part of the parsed json output, then maybe it could be saved as part of the `full_name` of the `CourseInstructor` model in open-discussions, which is used to populate the search index.

**Comment by pdpinch** [comment]
This was fixed by https://github.com/mitodl/open-discussions/pull/3378 as well as https://github.com/mitodl/ocw-to-hugo/pull/269
