### ISSUE TITLE
CHP: Display old course numbers

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#256]
Over time, some courses in OCW have been "renumbered." To help with findability, it's important that the old course numbers are maintained. In OCW legacy, these are rendered in HTML as "[new course number] (formerly [old course number]". See, for example, [16.89j S07](https://ocw.mit.edu/courses/aeronautics-and-astronautics/16-89j-space-systems-engineering-spring-2007/).

The data necessary for this is missing from the parsed JSON, until https://github.com/mitodl/ocw-data-parser/issues/137 is fixed. 

#### Acceptance Criteria:

- [ ] Include the former course number parenthetically after the current course number

#### Related issues 

- https://github.com/mitodl/open-discussions/issues/3381 The old course number should be searchable, just like the new one is

**Comment by pdpinch** [comment]
Note that the course 18-443-statistics-for-applications-spring-2015 is an interesting case. The course number in the URL is the _old_ course number. When this is implemented, this course should display the new course number, 18.650, as the primary number. See [OCW legacy](https://ocw.mit.edu/courses/mathematics/18-443-statistics-for-applications-spring-2015/) for reference)

**Comment by gumaerc** [comment]
Note that while https://github.com/mitodl/ocw-to-hugo/pull/279 will close this issue, there is a caveat with the way this is handled right now.  The structure of course number updates in the source data is an array of objects that look like:

```
    "new_course_numbers": [
        {
            "course_type_col": "Undergraduate",
            "new_course_number_col": "18.650",
            "old_course_number_col": "18.443",
            "sort_as_col": "18.650"
        }
    ],
```

Notice that this is an array, and seems to indicate it would support a course being re-numbered multiple times.  However, there are no OCW courses that currently put more than one item in here.  The code added in the above PR handles only a single re-number.  If multiple re-numbers from legacy data are desired in the future, support will have to be added to "crawl" the items in `new_course_numbers` and build a chain of updates.
