### ISSUE TITLE
generic resource file layout

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#286]
As a user of the ocw website, I'd like to be able to view metadata on resources other than PDF's on the OCW next website and be able to download them if I want.

#### Designs and Mockups
https://projects.invisionapp.com/d/main?origin=v7#/console/18609637/451119818/preview?scrollOffset=199

#### Acceptance Criteria:

- [ ] A markdown file is generated at the location of the file in the content tree, relative to its parent.  If it has no parent, make it a child of the course home page and place the markdown file at the root of the content folder
- [ ] The metadata relating to the file, shown in the design, is written into a property (something like `file_metadata`) in the front matter of these markdown files
- [ ] All markdown files created representing a file (except for PDFs) should have `type: course` and `layout: file`, or whatever we name the layout in the corresponding `ocw-hugo-themes` PR to come
- [ ] Links to said files in content are caught when being passed through `fixLinks` and rewritten to point at the Hugo page representing said file
- [ ] Both the `layout` name and the metadata key used to store the file's metadata should be consistent with what is implemented in a PR resolving https://github.com/mitodl/ocw-hugo-themes/issues/66

**Comment by pdpinch** [comment]
@gumaerc can this be closed?

**Comment by gumaerc** [comment]
The plan on this changed after creating this issue, as we ended up calling these "resources" and structuring things a bit differently.  So, this issue is obsolete and also creating resources for each file in a course was handled by this PR: https://github.com/mitodl/ocw-to-hugo/pull/337
