### ISSUE TITLE
links to legacy site in embedded_media

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#287]
### Steps to Reproduce

Convert a course that has a video page, like `8-01sc-classical-mechanics-fall-2016`

### Expected Behavior

The links to the various resources in `embedded_media` point to either an external location or an s3 path to an `open-learning-course-data` S3 bucket

### Actual Behavior

Some links point to external services, but some point directly to `ocw.mit.edu` and need to be resolved to an S3 link using `resolveRelativeLinks`

**Comment by pdpinch** [comment]
To be specific, we're trying to get links to captions/transcript files (.srt) to be usable with the embedded video player.
