### ISSUE TITLE
course images should be rendered as resources

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#338]
As part of the effort to adapt `ocw-to-hugo`'s output to match how `ocw-studio` publishes course sites, we will need to change the way course image metadata is generated.

#### Acceptance Criteria
 - [x] For the course image and course image thumbnail, resources are created at `content/resources/course_image.md` and `content/resources/course_image_thumbnail.md` respectively with the properties described [here](https://github.com/mitodl/ocw-hugo-projects/blob/706bb4f010c588d4362d66279bd256f6ca46ca89/ocw-course/ocw-studio.yaml#L18) relevant to images
 - [ ] A reference to the course image and thumbnail are stored in the appropriate place in `data/course.json` with the structure like the following, matching the UUID to the course image resource's UUID:
 ```
   "course_image": {
    "content": "2f94d70e-4dac-4161-930c-ff78e8646e1d"
  },
 ```

**Comment by noisecapella** [comment]
@gumaerc this makes sense to me. I would also set `website` in the `course_image` dict for compatibility with `RelationField` which would probably be used to select the resource in the metadata. 

I am concerned that the `course_image.md` and `course_image_thumbnail.md` filenames could collide with other resources we create. To address that we could have code in `ocw-to-hugo` and `ocw-studio` to have a blocklist of filenames we shouldn't use
