### ISSUE TITLE
remove pre-generated search urls

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#351]
Currently, in the course data template, `ocw-to-hugo` generates a number of properties as objects that contain a string and a search URL.  These properties, namely `department_numbers`, `level` and `course_feature_tags` should be changed to match the way `ocw-studio` publishes them based on the `ocw-course` site starter.  That is to say, they should just be simple lists of strings and not objects.  The search URL should be generated by `ocw-hugo-themes` during templating rather than being embedded in the data.

**Comment by pdpinch** [comment]
Does this issue include changes to ocw-to-hugo and the corresponding changes to ocw-hugo-themes?

**Comment by gumaerc** [comment]
@pdpinch This just refers to the changes in `ocw-to-hugo`.  There will be a follow-up PR in `ocw-hugo-themes` that adjusts the theme and references the new version of `ocw-to-hugo` after it is released.
