### ISSUE TITLE
some PDFs are missing resource pages

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#436]
On the legacy site, PDF files were sometimes stored on a separate file server, identified by a root path of `/ans7870/`.

Theses files should be identified by ocw-data-parser and the PDF files should be collected on S3. However, we don't seem to be creating resources to go with these files. 

On the nextgen site, these files shouldn't be treated any differently from other resources (unless they are an HTML file).  

### Steps to Reproduce

legacy: https://ocw.mit.edu/resources/res-6-001-continuum-electromechanics-spring-2009/textbook-contents/
nextgen: https://ocwnext-rc.odl.mit.edu/courses/res-6-001-continuum-electromechanics-spring-2009/pages/textbook-contents/

1. Visit  https://ocwnext-rc.odl.mit.edu/courses/res-6-001-continuum-electromechanics-spring-2009/pages/textbook-contents/
2. Click the link to "Front matter (PDF)"

### Expected Behavior

- browser loads an HTML page
- PDF is embedded in the HTML page

### Actual Behavior

- browser attempts to load a PDF
- PDF does not load 

### Related issues 

- many of these PDFs are "open textbooks" which we would like to collect into a resource list in the ocw-www site.
- https://github.com/mitodl/ocw-data-parser/issues/164 ans7870 files

**Comment by pdpinch** [comment]
@mbertrand does your work to backfill missing resources touch on this?

**Comment by mbertrand** [comment]
Sorry, missed your last comment.  No, the parser does not recognize ans7870 external links as resources, nor does it upload them.

**Comment by mbertrand** [comment]
Actually never mind, there is a resource for this pdf, going to close this.
