### ISSUE TITLE
verify that all the expected courses are exported, imported and published

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#445]
I'd like to be reassured that we've gotten everything we need from Plone. 

#### Acceptance Criteria:

- [ ] get a list from Plone of what we expect is published
- [ ] compare it to what what we have in the various buckets
- [ ] remove any duplicates (#443)
- [ ] identify anything that shouldn't be published (#150)

**Comment by pdpinch** [comment]
Here's a list of all the course in plone, filtered by "is it live=yes"

[Course-List-By-Publication-Status-1643990062936.xlsx](https://github.com/mitodl/ocw-to-hugo/files/8004464/Course-List-By-Publication-Status-1643990062936.xlsx)

**Comment by ChristopherChudzicki** [comment]
@pdpinch I did some work toward this, but am going to move on to other priorities as discussed.

Results so far:

**Completeness**:  All courses in [Course-List-By-Publication-Status-1643990062936.xlsx](https://github.com/mitodl/ocw-to-hugo/files/8004464/Course-List-By-Publication-Status-1643990062936.xlsx) have backups in our s3 buckets

*I'm not sure that list is complete, though. It only includes `/courses` urls; should it also include `/resouces` urls like https://ocw.mit.edu/resources/res-18-010-a-2020-vision-of-linear-algebra-spring-2020/index.htm?utm_source=SRLandingPage&utm_medium=CarouselSm&utm_campaign=FeaturedCourse ? *

**Duplicates:** I believe the only duplicates in the  `open-learning-course-data-rc` are:

```
# This courses have same UID
# the version with newer "last_published_date" is listed first

10-01-ethics-for-engineers-artificial-intelligence-spring-2020
10-01-ethics-for-engineers-spring-2020

res-mas-001-raise-responsible-ai-for-social-empowerment-and-education-spring-2022
res-mas-001-raise-responsible-ait-for-social-empowerment-and-education-spring-2022

24-908-creole-languages-and-caribbean-identities-spring-2017
24-908-creole-language-and-caribbean-identities-spring-2017

5-72-non-equilibrium-statistical-mechanics-spring-2012
5-72-statistical-mechanics-spring-2012

res-15-005-healthcare-finance-15-482x-spring-2019
res-15-005-healthcare-finance-spring-2019
```

if we still want to delete the older version, I can communicate with Tobias around that. 

_Work toward this is on the https://github.com/mitodl/ocw-to-hugo/tree/cc/check-courses branch_
