### ISSUE TITLE
root-relatives links from one course to another are broken

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#458]
I'm not sure how widespread this is, but I'm seeing it in multiple links on this page: https://github.mit.edu/mitocwcontent/18.03sc-fall-2011/blame/main/content/pages/syllabus/_index.md#L17 '

These are links which should have linked from one course to another. 

Ideally, these links would be changed to use the resource link shortcode, but I'm not sure that's feasible at this time.

**Comment by ChristopherChudzicki** [comment]
Closing this in favor of https://github.com/mitodl/ocw-studio/issues/1042
