### ISSUE TITLE
Data migration: missing videos in multiple courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#459]
checklist of videos:

- [x] [res-tll-004 (should be two not one)](https://ocwnext.odl.mit.edu/courses/res-tll-004-stem-concept-videos-fall-2013/video_galleries/videos/conservation/ )
- [x] [res-18-005 (should be 5)
](https://ocwnext.odl.mit.edu/courses/res-18-005-highlights-of-calculus-spring-2010/video_galleries/highlights_of_calculus/ )
- [x] 16.01
- [x] 2.627
- [x] 7.01sc 
- [x] [20.010j](https://ocwnext.odl.mit.edu/courses/20-010j-introduction-to-bioengineering-be-010j-spring-2006/video_galleries/videos/)

#### res-tll-004

Compare legacy: https://ocw.mit.edu/resources/res-tll-004-stem-concept-videos-fall-2013/videos/conservation/
to nextgen: https://ocwnext.odl.mit.edu/courses/res-tll-004-stem-concept-videos-fall-2013/video_galleries/videos/conservation/ 

The 2nd video "Latent Heat is missing" 

As far as I can tell the necessary data is in s3://open-learning-course-data-production/res-tll-004-stem-concept-videos-fall-2013/a29e75fbd826d2d192a930c18d6eb7d5_master.json but it does not appear in https://github.mit.edu/ocw-content-rc/res.tll-004-fall-2013/blob/main/content/video_galleries/videos/conservation.md

#### res-18-005

[parsed json](s3://open-learning-course-data-production/res-18-005-highlights-of-calculus-spring-2010 ./res-18-005-highlights-of-calculus-spring-2010/res-18-005-highlights-of-calculus-spring-2010_parsed.json) includes a video with uuid `37fc6a36f691f5053e109249f701dde6`

[markdown for video gallery](https://github.mit.edu/ocw-content-rc/res.18-005-spring-2010/blame/main/content/video_galleries/highlights_of_calculus.md#L11) includes uuid `37fc6a36-f691-f505-3e10-9249f701dde6` but there is [no corresponding resource](https://github.mit.edu/ocw-content-rc/res.18-005-spring-2010/search?q=37fc6a36-f691-f505-3e10-9249f701dde6&unscoped_q=37fc6a36-f691-f505-3e10-9249f701dde6) in the markdown

legacy (5 videos): https://ocw.mit.edu/resources/res-18-005-highlights-of-calculus-spring-2010/highlights_of_calculus/
nextgen (1 video): https://ocwnext.odl.mit.edu/courses/res-18-005-highlights-of-calculus-spring-2010/video_galleries/highlights_of_calculus/ 

#### 16.01

[markdown for page with embedded video](https://github.mit.edu/mitocwcontent/16.01-fall-2005/blame/cd667991741ba61dd3bb3694d39010f11f3f0965/content/pages/syllabus.md#L23) includes uuid `79dd98cc-6cbd-890e-d9f9-27583bf7336e` but there is [no corresponding resource](https://github.mit.edu/mitocwcontent/16.01-
fall-2005/search?q=79dd98cc&unscoped_q=79dd98cc) in the markdown

#### 2.627

embedded video, but no resource: https://github.mit.edu/mitocwcontent/2.627-fall-2013/search?q=e09ed427&unscoped_q=e09ed427

#### 7.01sc 

embedded video, but no resource: https://github.mit.edu/mitocwcontent/7.01sc-fall-2011/blame/main/content/pages/molecular-biology/dna-structure-classic-experiments.md#L68

**Comment by pdpinch** [comment]
Do you think #477 will also fix https://ocwnext.odl.mit.edu/courses/20-010j-introduction-to-bioengineering-be-010j-spring-2006/video_galleries/videos/ ?

**Comment by mbertrand** [comment]
Yes, just tried it:

<img width="811" alt="Screen Shot 2022-02-28 at 7 50 09 AM" src="https://user-images.githubusercontent.com/187676/155986364-f882eff3-436b-4e1b-b778-2879dc4f6d46.png">

**Comment by pdpinch** [comment]
I added checklist to make it clearer what needs to be done. I see the first one is working, but the 2nd one isn't. And then I ran out of time.

**Comment by dseaton** [comment]
@mbertrand @pdpinch There are two video missing in 8.06 Spring 2018. L13.4 and L13.5, which are easiest to see on this [page](https://ocw-studio.odl.mit.edu/sites/8-06-quantum-physics-iii-spring-2018/type/page/edit/775ae63a-83c3-7ea9-a86b-48e338f89741/). Let me know if there is a better way to report this or if this is the wrong place.

**Comment by pdpinch** [comment]
Closing this in favor of #511
