### ISSUE TITLE
Instructor Insights remove Student Counts image

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-to-hugo#461]
### Steps to Reproduce
1. Compare:
    - https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-034-artificial-intelligence-fall-2010/instructor-insights/ vs
    - https://ocw-published.odl.mit.edu/courses/6-034-artificial-intelligence-fall-2010/pages/instructor-insights/#student-information
2. or 
    - https://ocw.mit.edu/courses/womens-and-gender-studies/wgs-s10-history-of-women-in-science-and-engineering-fall-2017/instructor-insights/
    - vs https://ocw-published.odl.mit.edu/courses/wgs-s10-history-of-women-in-science-and-engineering-fall-2017/pages/instructor-insights/#student-information 

### Expected Behavior

Old image-based student counts should be migrated to student count shortocdes. 
Student information counts should not be images in ocw-next.

### Actual Behavior

Old image-based student counts are migrated as images.

_The images aren't appearing right now, but that's not the issue. The issue is that they should be migrated to shortocdes that render the counts as html / css_

### Other notes
We currently only have an `< approx-students >` shortode. But Some of the counts are not approximate (e.g., the "10" students in wgs-s10. Maybe change to a `< student-count >` shortode with an `approx` optional param.

**Comment by gumaerc** [comment]
FYI the images will start appearing again once https://github.com/mitodl/ocw-hugo-themes/pull/434 is released

**Comment by pdpinch** [comment]
Why is there a shortcode at all for these? It seems like basic markdown should be sufficient?

**Comment by pdpinch** [comment]
Also @ChristopherChudzicki do you think a find/replace management command can handle this?

**Comment by dseaton** [comment]
@pdpinch @ChristopherChudzicki I just asked the Instructor Insights team to remove these images manually. Should I roll that back? They have a couple edits on those pages: a) writing in the text enrollment numbers with text, b) changing some of the headings from h1 to h2, etc. While there they can delete these and make the other changes. Does that make sense to you both?

**Comment by ChristopherChudzicki** [comment]
@pdpinch I think there were shortcodes for these to make make a `div` appear like a circle image with count, similar to legacy site. Certainly markdown would be sufficient for text.

@dseaton I believe there are 65 remaining images on prod: https://docs.google.com/spreadsheets/d/1A1V7tqQNuExmdGs5B7LhXp9b7vkkMWRQyq9dCmjxAfE/edit?usp=sharing Some have already been changed to text ("14 students"). _Or I suppose maybe some already were 🤷 _. Unless I've missed a lot, IMO doing this programmatically is note worth the effort, at least if they're OK with text instead of circles.

Sorry for my absence on this thread... some of my github emails have been going to spam. I'll fix that....

**Comment by pdpinch** [comment]
Not urgent, but when you have a few minutes @ChristopherChudzicki can you update the count of these? I suspect more of them have been removed manually.

**Comment by ChristopherChudzicki** [comment]
@pdpinch Are you aware of any remaining student count images? I think they may all be gone.

1.  None of the `{{< resource >}}` or markdown images on instructor insight pages appear to be student counts
2. there are some pages representing the old approx images (example: https://github.mit.edu/mitocwcontent/6.034-fall-2010/blob/main/content/resources/300-approx.md) but the ones I've checked are not referenced anywhere in the markdown, and based on (1) I suspect none of these are used
3. No markdown links with "approx" or ending in `\d+.png` (like the old exact counts did) are count images

so... yeah. I think they might all be gone.

**Comment by ChristopherChudzicki** [comment]
@pdpinch I'm going to close this in light of ☝️ ... If I'm wrong, let me know / re-open.
