### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#464]
Some courses include code snippets. 

These should be rendered with appropriate HTML tags, and the styling should use a monospaced font. 

example 1:
legacy: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/syllabus/software/
nextgen: https://ocwnext.odl.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/pages/syllabus/software/#ide
markdown: https://github.mit.edu/mitocwcontent/6.006-fall-2011/blob/main/content/pages/syllabus/software.md

example 2:
legacy:
nextgen: https://ocwnext.odl.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/pages/readings/binary-search-trees/

**Comment by MAbdurrehman12** [comment]
> Where are you seeing the inline styling?

Initially, I saw it in the source code (by inspecting element) of the legacy course and after pulling the course from s3, the code snippets seem to have this inline-style.
e.g:   `<span style="font-family: Courier New,Courier;">sudo apt-get install -y python2.7 python-profiler</span>`

> Instead of inline styling it would be better to convert them to the correct markdown

This certainly is better, thank you

**Comment by gumaerc** [comment]
@MAbdurrehman12 This seems like a good strategy.  As you've probably noticed, there are already turndown rules labeled `codeblockfix` and `inlinecodeblockfix`.  These rules catch the typical code block HTML elements (`pre`, `kbd`, `tt`, `samp`) and notate them in markdown as code.  I think if there's some formatting in legacy OCW that's expecteding a span to be formatted with Courier New or Courier, code block notation will accomplish that regardless of the context so this should be fine.  If we find some examples of places where this style is set but the code block formatting doesn't look right, I think we can fix those one-off cases manually.
