### ISSUE TITLE
21W.758 S13 doesn't exist in studio production 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#470]
For some reason, this course doesn't seem to be have imported in production 

s3://open-learning-course-data-production/21w-758-genre-fiction-workshop-spring-2013/21w-758-genre-fiction-workshop-spring-2013_parsed.json

It does exist on ocw-studio-rc:

https://ocw-studio-rc.odl.mit.edu/sites/21w-758-genre-fiction-workshop-spring-2013/

**Comment by gumaerc** [comment]
From `21w-758-genre-fiction-workshop-spring-2013_parsed.json`:

`"last_unpublishing_date": "2015/04/16 07:00:44.510 GMT-4",`

Likely this course still exists on RC because in the Plone OCW system the course data isn't frequently backpopulated into QA.  So, the course was likely unpublished in production and the same thing never was done in QA.  `ocw-to-hugo` simply skips unpublished courses so they don't end up in the output bucket and are either not imported in the first place or removed from studio if they are detected as having been removed from the bucket.

**Comment by pdpinch** [comment]
Amazing. There are **two versions** of this course in Plone. [One was unpublished](https://ocwcms.mit.edu/courses/writing-and-humanistic-studies/21w-758-genre-fiction-workshop-spring-2013/view_module_comments), but [the other is still active](https://ocwcms.mit.edu/courses/comparative-media-studies-writing/21w-758-genre-fiction-workshop-spring-2013/view_module_comments). It's probably random which one we got in the Plone export. 

I'll try to update the raw JSON on S3 with the correct version, by running the export_content script. It will take until tomorrow to arrive.

**Comment by pdpinch** [comment]
Ok, both versions are in the Plone export, but they have the same slug. I'm not sure how we determine which one we get. 

As noted in #471, we should have imported the courses in the department CMS-W and not the courses in in 21W or CMS. 

In this particular case, that means

this one: s3://ocw-content-storage/PROD/CMS-W/21W.758/Spring_2013/21w-758-genre-fiction-workshop-spring-2013

instead of: s3://ocw-content-storage/PROD/21W/21W.758/Spring_2013/21w-758-genre-fiction-workshop-spring-2013

**Comment by mbertrand** [comment]
Found a few more?

https://ocw.mit.edu/courses/comparative-media-studies-writing/21w-730-1-expository-writing-social-and-ethical-issues-in-print-photography-and-film-fall-2005/
https://ocw.mit.edu/courses/comparative-media-studies-writing/21w-730-3-expository-writing-autobiography-theory-and-practice-spring-2001/
https://ocw.mit.edu/courses/comparative-media-studies-writing/cms-360-introduction-to-civic-media-fall-2012/
https://ocw.mit.edu/courses/comparative-media-studies-writing/cms-407-media-and-methods-sound-fall-2012/

Found these by doing a query on open-discussions for `LearningResourceRuns` which had duplicate slugs, of which at least one was published.  They are not on ocw-studio production.

**Comment by pdpinch** [comment]
Please go for it. I don’t think there’s any version of this course on production studio.

**Comment by mbertrand** [comment]
All the above sites are published now on production, I'll close this issue if they look good to you.

**Comment by pdpinch** [comment]
👍
