### ISSUE TITLE
replace << with « and >> with »

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#476]
There are several courses that include in-course navigation and make use of the « and » characters to make "next" and "previous" links clearer. These work fine. 

There are a couple of courses that are broken however. 

- [ ] [6.0001 F16](https://ocwnext.odl.mit.edu/courses/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/pages/in-class-questions-and-video-solutions/lecture-2-video-solutions/) uses `<<` and `>>`
- [ ] [6.042J S15](https://ocwnext.odl.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/pages/proofs/tp1-1/) uses `&lt;` and `&rt;` 
- [ ] [15.071 ](https://ocwnext.odl.mit.edu/courses/15-071-the-analytics-edge-spring-2017/pages/an-introduction-to-analytics/welcome-to-unit-1/) uses `&lt;` and `&rt;`
- [ ] [15.662x](https://ocw.mit.edu/courses/res-15-003-shaping-the-future-of-work-15-662x-spring-2016/pages/introduction-challenges-and-opportunities/challenges-and-opportunities-as-you-enter-the-workforce/) uses `&lt;` and `&rt;`

It seems like replacing `<<` and `&lt;` with « and replacing `>>` and `&rt;` with » would be an easy fix **in these cases.** Since the angle brackets are often escaped, we should also replace `\<\<` with «

#### an alternate solution 

We could also consider simply removing this within-course navigation since it's redundant. But that seems like it would require more discussion and input than this simple character replacement.

**Comment by ChristopherChudzicki** [comment]
@pdpinch Studio is not currently inserting extra escapes. I'll add some tests to enforce this when I work on https://github.com/mitodl/ocw-studio/issues/1238

A PR is up to clean up the existing bad escapes. The following courses will be affected:

```
course                                                                               , instances
15-071-the-analytics-edge-spring-2017                                                ,	510
6-004-computation-structures-spring-2017                                             ,	391
res-15-003-shaping-the-future-of-work-15-662x-spring-2016                            ,	97
mas-965-nextlab-i-designing-mobile-technologies-for-the-next-billion-users-fall-2008 ,	68
20-020-introduction-to-biological-engineering-design-spring-2009                     ,	20
6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016          ,	7
21g-064-intro-to-japanese-culture-spring-2012                                        ,	3
21w-035-science-writing-and-new-media-science-writing-for-the-public-spring-2018     ,	2
21m-342-composing-for-jazz-orchestra-fall-2008                                       ,	1
```

**Comment by ChristopherChudzicki** [comment]
This was done on prod. Results on are the "nextprev_prod" sheet of https://docs.google.com/spreadsheets/d/1JoOsJuoX81DBHmSbhpP9wkuIYmr7h8YkeQQRh36-YDY/edit?usp=sharing
