### ISSUE TITLE
resource download links to an HTML file 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#480]
### Steps to Reproduce

1 visit https://ocwnext.odl.mit.edu/courses/14-32-econometrics-spring-2007/resources/march1992cps/
2. click download button

### Expected Behavior

- browser should download the file `/courses/14-32-econometrics-spring-2007/2270da78216261412a057a388eb943e0_march1992cps.sas7bdat`

### Actual Behavior

- browser attempts to download `/courses/14-32-econometrics-spring-2007/2270da78216261412a057a388eb943e0_march1992cps.sas7bdat/index.html`

**Comment by pdpinch** [comment]
It seems like this is a Fastly issue.

**Comment by blarghmatey** [comment]
This is fixed. We were a little to conservative in our assumptions about what would constitute the number of characters in a file extension.
