### ISSUE TITLE
import video `start_time` and `end_time`

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#492]
import video start and end times from legacy OCW so we can control playback of video clips 

#### Acceptance Criteria:

- [ ] only update video resources that have a legacy `start_time` or `end_time`

#### Related Issues 

- blocked by https://github.com/mitodl/ocw-data-parser/issues/181

**Comment by pdpinch** [comment]
Do we need an update to ocw-hugo-projects to support this?

**Comment by MAbdurrehman12** [comment]
> Do we need an update to ocw-hugo-projects to support this?

I'm not sure, maybe yes, as the front-matter is being changed but @gumaerc will certainly have better insight on this
