### ISSUE TITLE
Pages in 16.90, 15.071, 6.042J don't convert to markdown

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#493]
### Steps to Reproduce

1. Run ocw-to-hugo on one or more of these courses: 
```
{
    "courses": [
        "6-042j-mathematics-for-computer-science-spring-2015",
        "16-90-computational-methods-in-aerospace-engineering-spring-2014",
        "15-071-the-analytics-edge-spring-2017"
    ]
}
```
2. In the output, examine pages like 

- `6-042j-mathematics-for-computer-science-spring-2015/content/pages/proofs/tp2-2/vertical-a28e46f96fa1.md`
- `6-042j-mathematics-for-computer-science-spring-2015/content/pages/proofs/tp4-3/set-theory-axioms-optional-0.md`
- `16-90-computational-methods-in-aerospace-engineering-spring-2014/content/pages/numerical-integration-of-ordinary-differential-equations/discretizing-odes/_index.md`
- `15-071-the-analytics-edge-spring-2017/content/pages/logistic-regression/modeling-the-expert-an-introduction-to-logistic-regression/quick-question-152.md`
- `14-01sc-principles-of-microeconomics-fall-2011/content/pages/unit-6-topics-in-intermediate-microeconomics/international-trade.md`

### Expected Behavior

- The pages should contain head matter, followed by markdown 
- If the HTML to markdown converter fails, it should log an error so we can debug and investigate

### Actual Behavior

- instead of markdown, the pages contain HTML

**Comment by pdpinch** [comment]
a slight larger list of courses with similar issues appears in https://github.com/mitodl/ocw-studio/issues/1119

**Comment by pdpinch** [comment]
Another course/page that might have the same issue? https://ocwnext.odl.mit.edu/courses/20-011j-statistical-thermodynamics-of-biomolecular-systems-be-011j-spring-2004/pages/simulations/

**Comment by mbertrand** [comment]
These are all pages with quizzes that aren't covered by existing turndown rules in ocw-to-hugo
