### ISSUE TITLE
Missing video in 6.041sc, RES.3-003, 18.01sc

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ocw-to-hugo#495]
### 6.041sc
**legacy**: https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/unit-i/lecture-1/uniform-probabilities-on-a-square/

page doesn't exist in nextgen, but there are links to it on https://ocw-studio.odl.mit.edu/sites/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/type/page/edit/b7578d11-fa1c-dee6-7b78-56ce34e8db48/?q=probability+models and https://ocw-studio.odl.mit.edu/sites/6-041sc-probabilistic-systems-analysis-and-applied-probability-fall-2013/type/page/edit/ae41cdf6-4102-6e80-720a-f98f3a837b7b/?q=resource

missing video youtube id: jxxrwZtpHH0 

### RES.3-003
**legacy**: https://ocw.mit.edu/resources/res-3-003-learn-to-build-your-own-videogame-with-the-unity-game-engine-and-microsoft-kinect-january-iap-2017/student-projects/long-project/Long-project-1-cats-cradle/

page doesn't exist in nextgen, but there was a link to it: https://github.mit.edu/mitocwcontent/res.3-003-january-iap-2017/blame/0720b4e8d0f224331aa3e1ccf8ff06241d2d4ab6/content/pages/student-projects/long-project.md#L46

In the parsed json, there appears to be an embedded media object with `"media_location": "GUgYT7GxUGA"` and `"uid": "c3e90e2854dca8a255b28504b2d1a707". I'm not sure why it didn't import. 

### 18.01sc
**legacy**: "Clip 1: definition of ex" https://ocw.mit.edu/courses/mathematics/18-01sc-single-variable-calculus-fall-2010/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-17-the-exponential-function-its-derivative-and-its-inverse/

There is a link on https://ocwnext.odl.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/pages/1.-differentiation/part-b-implicit-differentiation-and-inverse-functions/session-17-the-exponential-function-its-derivative-and-its-inverse/ but there is no page at https://ocwnext.odl.mit.edu/courses/18-01sc-single-variable-calculus-fall-2010/resources/clip-1-definition-of-ex

missing video youtube id: [9v25gg2qJYE](https://www.youtube.com/watch?v=9v25gg2qJYE&t=743s)

**Comment by pdpinch** [comment]
@mbertrand we've come across a few more. Are these covered by this issue, or are they due to something else?

RES.18-005
legacy: https://ocw.mit.edu/resources/res-18-005-highlights-of-calculus-spring-2010/introduction/
the video appears in parsed json, but not on [studio](https://ocw-studio.odl.mit.edu/sites/res-18-005-highlights-of-calculus-spring-2010/type/resource/?q=intro):
```
        {
          "uid": "c604afaf1ae9b9badb1e22d265c27aa2", 
          "title": "Video-YouTube-MP4", 
          "parent_uid": "b3b7b562782e72ede4e7d1d5ac69a228", 
          "media_location": "X9t-u87df3o", 
          "type": "Video", 
          "id": "Video-YouTube-MP4"
        }, 
```

RES.18-006
legacy: https://ocw.mit.edu/resources/res-18-006-calculus-revisited-single-variable-calculus-fall-2010/course-introduction/
the video appears in parsed json, but not on [studio](https://ocw-studio.odl.mit.edu/sites/res-18-006-calculus-revisited-single-variable-calculus-fall-2010/type/video_gallery/?q=intro) 
```
        {
          "uid": "254a3790a15340263799d746933547bf", 
          "title": "Video-YouTube-Stream", 
          "parent_uid": "71d3c4e5af5d30962a77926390116050", 
          "media_location": "MFRWDuduuSw", 
          "type": "Video", 
          "id": "Video-YouTube-Stream"
        }, 
```

Let me know if this deserves a new issue

**Comment by mbertrand** [comment]
RES.18-005: on production, the resource existed but most attributes were blank and it was soft-deleted (bad import at some point?).  I hard-deleted it.

After running `overwrite_ocw_course_content --create-new` on RES.18-005 and RES.18-006, both videos now exist, but they are not linked to from the side menu.  Not sure what's up with that.

https://ocwnext.odl.mit.edu/courses/res-18-005-highlights-of-calculus-spring-2010/resources/introduction/
https://ocwnext.odl.mit.edu/courses/res-18-006-calculus-revisited-single-variable-calculus-fall-2010/resources/course-introduction/

I wonder if `overwrite_ocw_course_content --create-new`  should just be run on all sites instead of using a filter.

**Comment by pdpinch** [comment]
Yeah, we can close this for now. When/if we find more, I'll reference this issue.
