### ISSUE TITLE
Enforcement of AWS access keypair environment variables does not work with EC2 instance profile

### ISSUE THREAD

**Issue by markbreedlove** [mitodl/ocw-to-hugo#68]
The application currently requires the `AWS_ACCESS_KEY` and `AWS_SECRET_ACCESS_KEY` variables to be set in `.env`, but these are not available if you are running an EC2 instance with an IAM Instance Profile. When running with an instance profile, you don't have an access key pair to maintain. The application should allow for these not to be set.  If the Node version of the `aws` client library works like the Python one, it is able to function automagically on an EC2 instance with an instance profile without these environment variables.

**Comment by gumaerc** [comment]
I didn't know about this, thanks.
