### ISSUE TITLE
index.md files being rendered

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ocw-to-hugo#76]
### Steps to Reproduce

Generate markdown for all OCW courses

### Expected Behavior

The Hugo part of the build executes without warnings or errors

### Actual Behavior

Some course sections have pages with a name of index which is causing ocw-to-hugo to render a index.md file like this:
```
---
title: Shear Dispersion Animation
course_id: 1-061-transport-processes-in-the-environment-fall-2008
type: course
layout: course_section
---
null
```
It causes warnings like this:
![image](https://user-images.githubusercontent.com/12089658/93375012-878f1100-f825-11ea-8d4d-a339f25caf80.png)

**Comment by pdpinch** [comment]
@gumaerc can this be closed?

**Comment by gumaerc** [comment]
@pdpinch This is an old issue, but I believe it has been fixed.  To check, I did a full run of `ocw-to-hugo` and searched the entire output folder for:

```
---
null
```
... and no results came up.  I think this had to do with media "pages" that had no actual content and we weren't transforming them yet at this point.
